//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZooBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Z80 OO library for: {0}
        ///Reflection Level: {1}
        ///Verbose: {2}
        ///Wait for key press: {3}
        ///Output File: {4}
        ///Output Directory: {5}
        ///Zoo Directory: {6}
        ///---------------------------------------------------------------------------------------.
        /// </summary>
        internal static string VerboseParams {
            get {
                return ResourceManager.GetString("VerboseParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{for equ in zoo_class.equs}}{{if equ.is_public}}{{equ.value.name}}			.equ {{equ.value.value}}
        ///{{end}}{{end}}
        ///
        ///;{{zoo_class.name}}.Properties
        ///{{for property in zoo_class.properties}}{{if property.is_public}}.globl {{zoo_class.name}}.{{property.value.name}}.offset:	.equ {{property.value.offset}}	; Size = {{property.value.size}}
        ///{{end}}
        ///
        ///.globl {{zoo_class.name}}
        ///.globl {{zoo_class.name}}.ClassNameStr
        ///.globl {{zoo_class.name}}.ParentClass
        ///.globl {{zoo_class.name}}.SisterClass
        ///.globl {{zoo_class.nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zoo_class_public_s {
            get {
                return ResourceManager.GetString("zoo_class_public_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///; ----------------------------------------------------------------
        ///; - Zoo Engine
        ///; ----------------------------------------------------------------
        ///	.include &quot;{{zoo.engine_path}}/zoo.{{zoo.reflection_level_name}}.asm&quot;
        ///	.include &quot;{{zoo.engine_path}}/zoo.macros.propertyaccessorsforclasses.asm&quot;
        ///	.include &quot;{{zoo.engine_path}}/zoo.macros.propertyaccessorsforobjects.asm&quot;
        ///	.include &quot;{{zoo.engine_path}}/zoo.macros.methodaccessorsforobjects.asm&quot;
        ///
        ///; --------------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zoo_class_s {
            get {
                return ResourceManager.GetString("zoo_class_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; ----------------------------------------------------------------
        ///; - Zoo Engine
        ///; ----------------------------------------------------------------
        ///	.include &quot;{{zoo.engine_path}}/zoo.{{zoo.reflection_level_name}}.asm&quot;
        ///	.include &quot;{{zoo.engine_path}}/zoo.macros.propertyaccessorsforclasses.asm&quot;
        ///	.include &quot;{{zoo.engine_path}}/zoo.macros.propertyaccessorsforobjects.asm&quot;
        ///	.include &quot;{{zoo.engine_path}}/zoo.macros.methodaccessorsforobjects.asm&quot;
        ///	
        ///; ---------------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zoo_package_asm {
            get {
                return ResourceManager.GetString("zoo_package_asm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZooBuilder version 0.1
        ///A Lightweight Object Orientation framework for Z80
        ///by DamnedAngel - 2019
        ///---------------------------------------------------------------------------------------
        ///.
        /// </summary>
        internal static string ZooBuilder {
            get {
                return ResourceManager.GetString("ZooBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Zoo building failed!
        ///Exiting with code {0}/0x{0:X8} ({1})..
        /// </summary>
        internal static string ZooBuildFail {
            get {
                return ResourceManager.GetString("ZooBuildFail", resourceCulture);
            }
        }
    }
}
